# Generated by Django 3.1.1 on 2020-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=32, null=True)),
                ('lname', models.CharField(blank=True, max_length=32, null=True)),
                ('department', models.CharField(blank=True, max_length=32, null=True)),
                ('designation', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'employee',
                # 'managed': False,
            },
        ),
    ]
